apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pts
  namespace: client-pts
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ "pts.dev.local" ]
      secretName: dev-local-tls
  rules:
    - host: pts.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: pts-web, port: { number: 80 } }
