apiVersion: apps/v1
kind: Deployment
metadata:
  name: pts-web
  namespace: client-pts
spec:
  replicas: 1
  selector:
    matchLabels: { app: pts-web }
  template:
    metadata:
      labels: { app: pts-web }
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports: [{ containerPort: 80 }]
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: conf
          configMap:
            name: pts-nginx-conf
