apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop-php
  namespace: client-pts
spec:
  replicas: 1
  selector:
    matchLabels: { app: prestashop-php }
  template:
    metadata:
      labels: { app: prestashop-php }
    spec:
      containers:
        - name: php
          image: prestashop-php:dev
          ports: [{ containerPort: 9000 }]
          env:
            - name: PTS_DB_HOST
              value: "ptsdb-mariadb.client-pts.svc.cluster.local"
            - name: PTS_DB_USER
              valueFrom: { secretKeyRef: { name: pts-db-secret, key: username } }
            - name: PTS_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: pts-db-secret, key: password } }
            - name: PTS_DB_NAME
              valueFrom: { secretKeyRef: { name: pts-db-secret, key: database } }
            - name: PS_INSTALL_AUTO
              value: "1"
            - name: PTS_DOMAIN
              value: "pts.dev.local"
