clients:
  - name: boulangerie
    apps: 
      - wordpress
    environments:
      - dev
      - prod
    
  - name: fashion-store
    apps:
      - wordpress
      - prestashop
    environments:
      - dev 

  - name: garage-moto
    apps:
      - prestashop
    environments:
      - dev