clients:
  - name: boulangerie
    # Lui ne veut que WP
    apps: 
      - wordpress
    environments:
      - dev
      - prod
    
  - name: fashion-store
    # Lui veut les deux !
    apps:
      - wordpress
      - prestashop
    environments:
      - dev 
      # Pas de prod pour l'instant