apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp
  namespace: client-wp
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ "wp.dev.local" ]
      secretName: dev-local-tls
  rules:
    - host: wp.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: wp-web, port: { number: 80 } }
