apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-web
  namespace: client-wp
spec:
  replicas: 1
  selector:
    matchLabels: { app: wp-web }
  template:
    metadata:
      labels: { app: wp-web }
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports: [{ containerPort: 80 }]
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: conf
          configMap:
            name: wp-nginx-conf
