apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-php
  namespace: client-wp
spec:
  replicas: 1
  selector:
    matchLabels: { app: wordpress-php }
  template:
    metadata:
      labels: { app: wordpress-php }
    spec:
      containers:
        - name: php
          image: wordpress-php:dev
          ports: [{ containerPort: 9000 }]
          env:
            - name: WORDPRESS_DB_HOST
              value: "wpdb-mariadb.client-wp.svc.cluster.local"
            - name: WORDPRESS_DB_USER
              valueFrom: { secretKeyRef: { name: wp-db-secret, key: username } }
            - name: WORDPRESS_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: wp-db-secret, key: password } }
            - name: WORDPRESS_DB_NAME
              valueFrom: { secretKeyRef: { name: wp-db-secret, key: database } }
