resources:
  - ../../base

images:
  - name: wordpress-php
    newName: ghcr.io/pmi-git/dst-project-webapp/wordpress-php
    newTag: dev
  - name: prestashop-php
    newName: ghcr.io/pmi-git/dst-project-webapp/prestashop-php
    newTag: dev
