name: CI/CD - Deploy to K3s

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Installer les dépendances du script
    - name: Install dependencies
      run: |
        pip install pyyaml

    # 4. Configurer kubectl avec le secret
    - name: Setup Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config

    # --- AJOUT DE TRIVY ---
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0 # Version stable recommandée
      with:
        scan-type: 'config'        # Mode configuration (pour les fichiers K8s/Terraform)
        scan-ref: 'k8s-templates/' # On scanne uniquement ton dossier de templates
        format: 'table'            # Affichage tableau dans les logs
        exit-code: '0'  # On ne bloque plus le déploiement, on alerte juste
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'  
      # ----------------------
    
    # 5. Lancer le script de deploy
    - name: Run deployment script
      env:
        # On passe TOUS les secrets au script, il choisira le bon selon la branche
        KUBECONFIG_DEV: ${{ secrets.KUBECONFIG_DEV }}
        VPS_IP_DEV: ${{ secrets.VPS_IP_DEV }}
        KUBECONFIG_PROD: ${{ secrets.KUBECONFIG_PROD }}
        VPS_IP_PROD: ${{ secrets.VPS_IP_PROD }}
      run: |
          python3 scripts/deploy.py

    # 6. Lancer les smoke test
    - name: Run Smoke Tests
      env:
        # On passe aussi les deux IPs au test
        VPS_IP_DEV: ${{ secrets.VPS_IP_DEV }}
        VPS_IP_PROD: ${{ secrets.VPS_IP_PROD }}
      run: |
        pip install requests pyyaml
        python3 scripts/smoke_test.py
