name: CI/CD - Deploy to K3s

on:
  push:
    branches:
      - main
      - 'feature/k3s'
      - 'feature/smoke'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Installer les dépendances du script
    - name: Install dependencies
      run: |
        pip install pyyaml

    # 4. Configurer kubectl avec le secret
    - name: Setup Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config

    # --- AJOUT DE TRIVY ---
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0 # Version stable recommandée
      with:
        scan-type: 'config'        # Mode configuration (pour les fichiers K8s/Terraform)
        scan-ref: 'k8s-templates/' # On scanne uniquement ton dossier de templates
        format: 'table'            # Affichage tableau dans les logs
        exit-code: '1'             # ⚠️ IMPORTANT : 1 = Fait échouer la pipeline si faille trouvée
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'  # On ne bloque que pour les trucs graves
      # ----------------------
    
    # 5. Lancer le script de deploy
    - name: Run Deploy Script
      env:
        KUBECONFIG: /home/runner/.kube/config # On force le chemin pour être sûr
      run: |
        python3 scripts/deploy.py

    # 6. Lancer les smoke test
    - name: Run Smoke Tests
      env:
        VPS_IP: ${{ secrets.VPS_IP }} # secret, sinon en dur dans le script
      run: |
        pip install requests pyyaml
        python3 scripts/smoke_test.py
